inherit_from: .rubocop_todo.yml
Documentation:
  Enabled: false
AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
  Style:
    - 'FrozenStringLiteralComment'